name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  rust_version: "1.82.0"

jobs:
  pre_job:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }} && ! (startsWith(github.ref, 'refs/tags/') && github.event_name == 'push')
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          concurrent_skipping: "same_content_newer"
          skip_after_successful_duplicate: "false"

  cross:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    name: cross
    runs-on: ubuntu-latest
    container: "node:current-bookworm-slim"
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: arm64
            target: aarch64-unknown-linux-gnu
            gcc: aarch64-linux-gnu
            pkgconfig: aarch64-linux-gnu
    steps:
      - uses: actions/checkout@v4
      - name: Install basic tools
        run: |
          apt-get update
          apt-get install --assume-yes --no-install-recommends curl ca-certificates protobuf-compiler
      - name: Install ${{ matrix.arch }} cross compiler and gstreamer
        id: setup
        run: |
          dpkg --add-architecture ${{ matrix.arch }}
          apt-get update
          apt-get install --assume-yes --no-install-recommends \
          build-essential \
          gcc-${{ matrix.gcc }} \
          g++-${{ matrix.gcc }} \
          libgstrtspserver-1.0-dev:${{ matrix.arch }} \
          libgstreamer1.0-dev:${{ matrix.arch }} \
          libgtk2.0-dev:${{ matrix.arch }} \
          libglib2.0-dev:${{ matrix.arch }} \
          libssl-dev:${{ matrix.arch }}
      - name: Install rustup
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- --no-modify-path --quiet -y
          echo "${HOME}/.cargo/bin" >> "${GITHUB_PATH}"
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
          key: cargo-registry-${{ matrix.arch }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-registry-${{ matrix.arch }}-
      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: cargo-build-${{ matrix.arch }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-build-${{ matrix.arch }}-
      - name: Install ${{ matrix.arch }} Rust toolchain
        run: |
          rustup default "${{ env.rust_version }}"
          rustup target add ${TARGET}
        env:
          TARGET: ${{ matrix.target }}
      - name: Build
        run: |
          cargo build --release --verbose --all-features --target=${TARGET}
        env:
          # Retarget pkg-config as described in https://www.freedesktop.org/wiki/Software/pkg-config/CrossCompileProposal/
          PKG_CONFIG_ALLOW_CROSS: 1
          PKG_CONFIG_LIBDIR: /usr/lib/${{ matrix.pkgconfig }}/pkgconfig
          TARGET: ${{ matrix.target }}
          JEMALLOC_SYS_WITH_LG_PAGE: 16
      - uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.arch }}-bookworm
          path: "target/${{ matrix.target }}/release/neolink*"

  push_to_registry:
    name: Build Docker image
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs:
      - "cross"
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Convert repo to lower case for docker
        id: string_repo
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set image name
        id: docker_repo
        shell: bash
        run: |
          echo "DOCKER_NWO=ghcr.io/${GITHUB_NWO}" >> $GITHUB_OUTPUT
        env:
          GITHUB_NWO: ${{ steps.string_repo.outputs.lowercase }}
      - name: Get tag name
        id: tags
        shell: bash
        run: |
          tags=( )
          gittag="$(git tag --points-at HEAD)"
          branch="$(git rev-parse --abbrev-ref HEAD)"

          if [[ -n "${gittag}" ]]; then
            tags=( "${tags[@]}" "${REPO_NAME}:${gittag}" )
          fi
          if [[ -n "${branch}" ]]; then
            branch="$(echo "${branch}" | sed -E 's|[/]|-|g')"
            tags=( "${tags[@]}" "${REPO_NAME}:${branch}" )
            if [ "${branch}" == "master" ]; then
              tags=( "${tags[@]}" "${tags},${REPO_NAME}:latest" )
            fi
          fi
          function join_by {
            local d=${1-} f=${2-}
            if shift 2; then
              printf %s "$f" "${@/#/$d}"
            fi
          }
          tagstr="$(join_by "," "${tags[@]}")"
          echo "TAGS=${tagstr}"
          echo "TAGS=${tagstr}"  >> "${GITHUB_OUTPUT}"
        env:
          REPO_NAME: ${{ steps.docker_repo.outputs.DOCKER_NWO }}
      - name: Get project version
        id: toml
        run: |
          NEOLINK_VERSION="$(grep '^version' Cargo.toml | head -1 | sed 's/version = "\(.*\)"/\1/')"
          echo "version=${NEOLINK_VERSION}" >> $GITHUB_OUTPUT
      - name: Prepare directory
        run: |
          mkdir -p linux/arm64
      - name: Download Linux arm64
        uses: actions/download-artifact@v4
        with:
          name: release-arm64-bookworm
          path: linux/arm64
      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          platforms: linux/arm64
          context: .
          push: true
          file: Dockerfile
          tags: ${{ steps.tags.outputs.TAGS }}
          build-args: VERSION=${{ steps.toml.outputs.version }}, REPO=${{ github.repository }}, OWNER=${{ github.repository_owner }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
        env:
          DOCKER_BUILDKIT: 1

  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') && github.event_name == 'push' # Ensure this only runs on a tag or expect issues
    needs:
      - "cross"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get project version
        id: toml
        run: |
          NEOLINK_VERSION="$(grep '^version' Cargo.toml | head -1 | sed 's/version = "\(.*\)"/\1/')"
          echo "version=${NEOLINK_VERSION}" >> $GITHUB_OUTPUT
      - name: Download Linux arm64
        uses: actions/download-artifact@v4
        with:
          name: release-arm64-bookworm
          path: neolink_linux_arm64
      - name: Prepare releases
        run: |
          dirs=(
            neolink_linux_arm64
          )
          for d in "${dirs[@]}"; do
            chmod +x "${d}/neolink"*
            zip -r "${d}.zip" "${d}"
          done
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          name: Neolink ${{steps.toml.outputs.version}}
          files: |
            neolink_linux_arm64.zip
          body: |
            Neolink release ${{steps.toml.outputs.version}}
          draft: true
          prerelease: ${{ contains(github.ref_name,  'rc') }}
